### ISSUE TITLE
혹시 assistant 삭제하셨나요?

### ISSUE THREAD

**Issue by RektPunk** [sebanimm/ai-bocchi#1]
블로그 보고 왔습니다.. 실행해보려고 하는데 안되어서요,
```
openai.NotFoundError: Error code: 404 - {'error': {'message': "No assistant found with id 'asst_PZVM3XAS1O7UtY4IA4F4QwSP'.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

**Comment by sebanimm** [comment]
아마 제 계정에 생성한 어시스턴트라 접근이 안되시는 것 같네요... 
본인 계정의 어시스턴트만 가능한 것 같아요

**Comment by RektPunk** [comment]
아쉽네요... 가져다 쓰려고 했는데ㅎㅎ 다른 방법을 찾아봐야겠네요, 감사합니다!
<img width="928" alt="image" src="https://github.com/user-attachments/assets/9ef304f6-400b-4b14-b185-3fcc4b4dac06">
